name: Minimal dependency check

on:
  push:
    branches: [main, "release/*"]
  pull_request:
    branches: [main, "release/*"]

defaults:
  run:
    shell: bash

jobs:
  minimal-test:
    runs-on: ubuntu-latest

    timeout-minutes: 30

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Install uv and setup python
        uses: astral-sh/setup-uv@37802adc94f370d6bfd71619e3f0bf239e1f3b78 # v7.6.0
        with:
          activate-environment: true
          python-version: "3.12"
          enable-cache: true

      - name: Install LitServe
        run: |
          uv sync --no-dev
          uv pip install . psutil  -U -q
          uv pip list

      - name: Tests
        run: python tests/minimal_run.py
